language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers libboost-chrono1.48-dev libboost-date-time1.48-dev libboost-filesystem1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-program-options1.48-dev libboost-test1.48-dev python-yaml lcov
    - gem install coveralls-lcov
script:
    - mkdir -p build && cd build
    - cmake -DTEST_COVERAGE=ON ..
    - make && ./examples/devlist && ctest --output-on-failure
after_success:
    - lcov --directory tests --base-directory ../vexcl --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr*' '*/cl.hpp' -o coverage.info
    - cd .. && coveralls-lcov build/coverage.info
